### PR TITLE
Update package versions

### PR DESCRIPTION
**Pull request by oscar6echo**

### CODE REVIEW

**Comment by PierreMarion23** [comment]
Currently checking the binder is still working with the new package version

**Comment by PierreMarion23** [comment]
Looks like the binder is not working... Both custom and core ipywidgets not working in the binder.
I got the following behavior:
+ testing `! pip freeze` and `! jupyter nbextension list` give expected result
+ but when I try to instantiate either a custom or core slider, I get the following error:

screenshot from 2018-01-28 20-03-09

**Comment by oscar6echo** [comment]
I don't really know what caused the bug.  
I republished jupyter_widget_d3_slider (0.1.7), and also bump notebook version so as to not need the enable, which I left in the postBuild as comments.
Tested on mybinder.org: https://mybinder.org/v2/gh/oscar6echo/jupyter-d3-slider-binder/patch-1.  
It works fine this time. But pls double check before merging.

**Comment by PierreMarion23** [comment]
Seems to be working now.

**Pull request merged**
